---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: arunvel1988/alpine_solr
    replicas: 3

  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true

    - name: Start Minikube if it's not running.
      command: minikube start
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

  tasks:
    

    # Create Kubernetes resources to run Solr
    - name: Create a Deployment for Solr
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: solr
            namespace: default
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: solr
            template:
              metadata:
                labels:
                  app: solr
              spec:
                containers:
                - name: solr
                  image: "{{ image_name }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 8983

    - name: Create a Service for Solr
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: solr
            namespace: default
          spec:
            ports:
            - name: "solr"
              port: 8983
              protocol: TCP
              targetPort: 8983
            
            selector:
              app: solr
            type: NodePort

  post_tasks:
    - name: Expose solr on the host via Minikube.
      command: minikube service solr --url=true
      changed_when: false
      register: minikube_service

    - debug:
        msg: "Solr URL: {{ minikube_service['stdout_lines'][0] }}"
